//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAPPWITHIMAGES.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [DisplayName("ID")]
        public int id { get; set; }
        [DisplayName("Product Name")]
        [Required(ErrorMessage="Product Name is required")]
        public string ProductTitle { get; set; }
        public string Price { get; set; }
        public string Stock { get; set; }
        public string Image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
